# Generated by Django 5.2.5 on 2025-08-26 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_manager_user_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_patient',
            new_name='is_customer',
        ),
    ]
