# Generated by Django 5.2.5 on 2025-10-04 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_is_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_receptionist',
            new_name='is_hospital_staff',
        ),
    ]
