# Generated by Django 5.2.5 on 2025-09-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_is_patient_user_is_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('receptionist', 'Receptionist'), ('admin', 'Administrator')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
