# Generated by Django 5.2.5 on 2025-09-26 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_initial'),
        ('hospital', '0009_remove_billroomitem_days_remove_billroomitem_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.patient'),
        ),
    ]
