# Generated by Django 5.2.5 on 2025-10-04 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_testimonial_patient'),
        ('doctor', '0006_doctor_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.doctor'),
        ),
    ]
