# Generated by Django 5.2.5 on 2025-09-14 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorsInHospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'hospital doctor',
                'verbose_name_plural': 'hospital doctors',
                'db_table': 'hospital_doctors',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('place', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'patient',
                'verbose_name_plural': 'patients',
                'db_table': 'patients_patient',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('room_type', models.CharField(choices=[('GENERAL', 'General Ward'), ('SEMI', 'Semi-Private'), ('PRIVATE', 'Private Room'), ('ICU', 'ICU'), ('DELUXE', 'Deluxe Room')], default='GENERAL', max_length=20)),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_occupied', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'hospital room',
                'verbose_name_plural': 'hospital rooms',
                'db_table': 'hospital_rooms',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('token_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='pending', max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.patient')),
            ],
            options={
                'verbose_name': 'patient appointment',
                'verbose_name_plural': 'patient appointments',
                'db_table': 'patient_appointments',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('medicines_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tests_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('injections_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('intravenous_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('room_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('surgery_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nursing_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('misc_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance_due', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('bill_number', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.appointment')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='doctor.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_bills', to='hospital.patient')),
            ],
            options={
                'verbose_name': 'appointment bill',
                'verbose_name_plural': 'appointment bills',
                'db_table': 'appointment_bills',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BillInjectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('injection_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injection_items', to='hospital.appointmentbill')),
            ],
            options={
                'verbose_name': 'injection bill',
                'verbose_name_plural': 'injection bills',
                'db_table': 'injection_bills',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BillIntravenousItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iv_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intravenous_items', to='hospital.appointmentbill')),
            ],
            options={
                'verbose_name': 'iv bill',
                'verbose_name_plural': 'iv bills',
                'db_table': 'iv_bills',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BillMedicineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_items', to='hospital.appointmentbill')),
            ],
            options={
                'verbose_name': 'medicine bill',
                'verbose_name_plural': 'medicine bills',
                'db_table': 'medicine_bills',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BillMiscItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='misc_items', to='hospital.appointmentbill')),
            ],
            options={
                'verbose_name': 'misc bill',
                'verbose_name_plural': 'misc bills',
                'db_table': 'misc_bills',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BillNursingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('visits', models.IntegerField(default=1)),
                ('charge_per_visit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nursing_items', to='hospital.appointmentbill')),
            ],
            options={
                'verbose_name': 'visit bill',
                'verbose_name_plural': 'visit bills',
                'db_table': 'visit_bills',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BillSurgeryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surgery_name', models.CharField(max_length=255)),
                ('surgeon_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ot_hours', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('ot_charge_per_hour', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('surgeon_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('anesthesia_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgery_items', to='hospital.appointmentbill')),
            ],
            options={
                'verbose_name': 'ot bill',
                'verbose_name_plural': 'ot bills',
                'db_table': 'ot_bills',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BillTestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_items', to='hospital.appointmentbill')),
            ],
            options={
                'verbose_name': 'test bill',
                'verbose_name_plural': 'test bills',
                'db_table': 'test_bills',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('insurance', 'Insurance')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='hospital.appointmentbill')),
            ],
            options={
                'verbose_name': 'bill payment',
                'verbose_name_plural': 'bill payments',
                'db_table': 'bill_payments',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text="Doctor's additional notes or instructions", null=True)),
                ('duration', models.CharField(blank=True, help_text='e.g., 5 days', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='hospital.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='hospital.patient')),
            ],
            options={
                'verbose_name': 'patient prescription',
                'verbose_name_plural': 'patient prescriptions',
                'db_table': 'patient_prescriptions',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.CharField(max_length=255)),
                ('dosage', models.CharField(help_text='e.g., 500mg', max_length=100)),
                ('frequency', models.CharField(help_text='e.g., twice daily', max_length=100)),
                ('instructions', models.TextField(blank=True, help_text='Additional instructions if any', null=True)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='hospital.prescription')),
            ],
            options={
                'verbose_name': ' prescription item',
                'verbose_name_plural': ' prescription items',
                'db_table': 'prescription_items',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BillRoomItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_items', to='hospital.appointmentbill')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.room')),
            ],
            options={
                'verbose_name': 'room bill',
                'verbose_name_plural': 'room bills',
                'db_table': 'room_bills',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='doctor.doctor')),
            ],
            options={
                'verbose_name': 'doctor availability',
                'verbose_name_plural': 'doctors availability',
                'db_table': 'doctors_availability',
                'ordering': ['-id'],
                'unique_together': {('doctor', 'weekday')},
            },
        ),
    ]
