# Generated by Django 5.2.5 on 2025-11-21 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionitem',
            name='medicine',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='hospital.medicine'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DoctorsInHospital',
        ),
    ]
