# Generated by Django 5.2.5 on 2025-09-25 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='image',
        ),
    ]
