# Generated by Django 5.2.5 on 2025-09-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_doctoravailability_consult_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoravailability',
            name='lunch_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='lunch_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
