# Generated by Django 5.2.5 on 2025-09-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_doctoravailability_lunch_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token_number',
            field=models.CharField(max_length=20),
        ),
    ]
