# Generated by Django 5.2.5 on 2025-09-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_alter_token_token_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_duration',
            field=models.IntegerField(default=0),
        ),
    ]
