# Generated by Django 5.2.5 on 2025-09-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_remove_department_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='base_fee',
        ),
        migrations.AddField(
            model_name='hospital',
            name='registration_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
