# Generated by Django 5.2.5 on 2025-09-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_remove_department_base_fee_hospital_registration_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='registration_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
