# Generated by Django 5.2.5 on 2025-09-25 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_alter_hospital_registration_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='hospital',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorsinhospital',
            name='hospital',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='hospital',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital'),
            preserve_default=False,
        ),
    ]
