# Generated by Django 5.2.5 on 2025-09-25 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_department_hospital_doctorsinhospital_hospital_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
