# Generated by Django 5.2.5 on 2025-09-25 17:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_initial'),
        ('hospital', '0008_department_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billroomitem',
            name='days',
        ),
        migrations.RemoveField(
            model_name='billroomitem',
            name='room',
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('PRIVATE', 'Private Room'), ('DELUXE', 'Deluxe Room')], default='PRIVATE', max_length=20),
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True)),
                ('admit_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('discharge_datetime', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ADMITTED', 'Admitted'), ('DISCHARGED', 'Discharged'), ('CANCELLED', 'Cancelled')], default='ADMITTED', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('admitting_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='hospital.patient')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.room')),
            ],
            options={
                'verbose_name': 'hospital admission',
                'verbose_name_plural': 'hospital admissions',
                'db_table': 'hospital_admissions',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='billroomitem',
            name='admission',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hospital.admission'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='GeneralWard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('total_beds', models.PositiveIntegerField(default=0)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital')),
            ],
            options={
                'verbose_name': 'hospital general',
                'verbose_name_plural': 'hospital generals',
                'db_table': 'hospital_generals',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='admission',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.generalward'),
        ),
        migrations.CreateModel(
            name='GeneralWardBed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(max_length=10)),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='hospital.generalward')),
            ],
            options={
                'verbose_name': 'general bed',
                'verbose_name_plural': 'general beds',
                'db_table': 'general_beds',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='admission',
            name='ward_bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.generalwardbed'),
        ),
        migrations.CreateModel(
            name='ICU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icu_type', models.CharField(choices=[('MICU', 'Medical ICU'), ('SICU', 'Surgical ICU'), ('CCU', 'Cardiac ICU')], max_length=20)),
                ('floor', models.IntegerField(default=0)),
                ('total_beds', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital')),
            ],
            options={
                'verbose_name': 'hospital icu',
                'verbose_name_plural': 'hospital icus',
                'db_table': 'hospital_icus',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='admission',
            name='icu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.icu'),
        ),
        migrations.CreateModel(
            name='ICUBed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('has_ventilator', models.BooleanField(default=False)),
                ('has_monitor', models.BooleanField(default=True)),
                ('has_oxygen_supply', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('icu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icubeds', to='hospital.icu')),
            ],
            options={
                'unique_together': {('icu', 'bed_number')},
            },
        ),
        migrations.AddField(
            model_name='admission',
            name='icu_bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.icubed'),
        ),
    ]
