# Generated by Django 5.2.5 on 2025-09-26 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_remove_billroomitem_days_remove_billroomitem_room_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctoravailability',
            old_name='lunch_end',
            new_name='break_end',
        ),
        migrations.RenameField(
            model_name='doctoravailability',
            old_name='lunch_start',
            new_name='break_start',
        ),
    ]
