# Generated by Django 5.2.5 on 2025-09-28 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_remove_patient_user_patient_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorsinhospital',
            name='fee',
        ),
    ]
