# Generated by Django 5.2.5 on 2025-09-28 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0012_remove_doctorsinhospital_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentbill',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_bills', to='hospital.patient'),
        ),
        migrations.AlterField(
            model_name='appointmentbill',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI')], max_length=20),
        ),
    ]
