# Generated by Django 5.2.5 on 2025-09-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0013_alter_appointmentbill_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentbill',
            name='bill_number',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='appointmentbill',
            unique_together={('appointment', 'bill_number')},
        ),
    ]
