# Generated by Django 5.2.5 on 2025-09-28 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0014_alter_appointmentbill_bill_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentbill',
            name='token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.token'),
        ),
    ]
