# Generated by Django 5.2.5 on 2025-10-02 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0015_appointmentbill_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentbill',
            name='token',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='token_number',
            field=models.CharField(max_length=20),
        ),
    ]
