# Generated by Django 5.2.5 on 2025-10-05 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0016_remove_appointmentbill_token_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalwardbed',
            old_name='daily_rate',
            new_name='rate_per_hour',
        ),
        migrations.RenameField(
            model_name='icubed',
            old_name='daily_rate',
            new_name='rate_per_hour',
        ),
    ]
