# Generated by Django 5.2.5 on 2025-10-05 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0017_rename_daily_rate_generalwardbed_rate_per_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalward',
            name='floor',
            field=models.IntegerField(default=0),
        ),
    ]
