# Generated by Django 5.2.5 on 2025-10-05 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_generalward_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalwardbed',
            name='has_oxygen_supply',
            field=models.BooleanField(default=True),
        ),
    ]
