# Generated by Django 5.2.5 on 2025-10-05 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_generalwardbed_has_oxygen_supply'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalwardbed',
            name='has_monitor',
            field=models.BooleanField(default=True),
        ),
    ]
