# Generated by Django 5.2.5 on 2025-10-05 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_doctor_fee'),
        ('hospital', '0021_facility_room_facilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='doctor.doctor'),
        ),
        migrations.AlterField(
            model_name='icu',
            name='icu_type',
            field=models.CharField(choices=[('MICU', 'Medical ICU'), ('SICU', 'Surgical ICU'), ('CICU', 'Cardiac ICU')], max_length=20),
        ),
    ]
