# Generated by Django 5.2.5 on 2025-10-05 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0022_patient_doctor_alter_icu_icu_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='doctor',
        ),
    ]
