# Generated by Django 5.2.5 on 2025-10-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0023_remove_patient_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionitem',
            name='dosage',
            field=models.CharField(blank=True, help_text='e.g., 500mg', max_length=100, null=True),
        ),
    ]
