# Generated by Django 5.2.5 on 2025-10-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0024_alter_prescriptionitem_dosage'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='title',
            field=models.CharField(blank=True, help_text='e.g., Prescription for Flu', max_length=255, null=True),
        ),
    ]
