# Generated by Django 5.2.5 on 2025-10-08 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0025_prescription_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionitem',
            name='frequency',
            field=models.CharField(blank=True, help_text='e.g., twice daily', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='medicine',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
