# Generated by Django 5.2.5 on 2025-10-09 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_doctor_fee'),
        ('hospital', '0026_alter_prescriptionitem_frequency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billnursingitem',
            old_name='description',
            new_name='nursing_care',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='admitting_doctor',
        ),
        migrations.AlterUniqueTogether(
            name='billmiscitem',
            unique_together={('bill', 'description')},
        ),
        migrations.RemoveField(
            model_name='billsurgeryitem',
            name='surgeon_name',
        ),
        migrations.AddField(
            model_name='admission',
            name='is_emergency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='billmiscitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='billmiscitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admission',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='hospital.patient'),
        ),
        migrations.AlterUniqueTogether(
            name='billinjectionitem',
            unique_together={('bill', 'injection_name')},
        ),
        migrations.AlterUniqueTogether(
            name='billintravenousitem',
            unique_together={('bill', 'iv_name')},
        ),
        migrations.AlterUniqueTogether(
            name='billmedicineitem',
            unique_together={('bill', 'medicine_name')},
        ),
        migrations.AlterUniqueTogether(
            name='billnursingitem',
            unique_together={('bill', 'nursing_care')},
        ),
        migrations.AlterUniqueTogether(
            name='billroomitem',
            unique_together={('bill', 'admission')},
        ),
        migrations.AlterUniqueTogether(
            name='billtestitem',
            unique_together={('bill', 'test_name')},
        ),
        migrations.AlterUniqueTogether(
            name='prescription',
            unique_together={('patient', 'appointment')},
        ),
        migrations.AlterUniqueTogether(
            name='prescriptionitem',
            unique_together={('prescription', 'medicine', 'dosage', 'frequency')},
        ),
        migrations.CreateModel(
            name='AdmissionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_requests', to='hospital.appointment')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.doctor')),
                ('preferred_icu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.icu')),
                ('preferred_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.room')),
                ('preferred_ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.generalward')),
            ],
            options={
                'verbose_name': 'admission request',
                'verbose_name_plural': 'admission requests',
                'db_table': 'admission_requests',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='admission',
            name='admitting_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.admissionrequest'),
        ),
        migrations.RemoveField(
            model_name='billmiscitem',
            name='amount',
        ),
    ]
