# Generated by Django 5.2.5 on 2025-10-09 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0027_rename_description_billnursingitem_nursing_care_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tokens', to='hospital.patient'),
        ),
    ]
