# Generated by Django 5.2.5 on 2025-10-09 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0029_appointment_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='hospital.token'),
        ),
    ]
