# Generated by Django 5.2.5 on 2025-10-09 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0030_alter_appointment_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='patient',
        ),
    ]
