# Generated by Django 5.2.5 on 2025-10-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0031_remove_token_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='stripe_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
