# Generated by Django 5.2.5 on 2025-10-09 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0032_payment_stripe_intent_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='departemnt',
            new_name='department',
        ),
    ]
