# Generated by Django 5.2.5 on 2025-10-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0033_rename_departemnt_token_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='is_lock',
            field=models.BooleanField(default=False),
        ),
    ]
