# Generated by Django 5.2.5 on 2025-10-13 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0034_token_is_lock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='is_lock',
            new_name='is_locked',
        ),
    ]
