# Generated by Django 5.2.5 on 2025-08-27 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_alter_doctor_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorsinhospital',
            options={'ordering': ['-id'], 'verbose_name': 'hospital doctor', 'verbose_name_plural': 'hospital doctors'},
        ),
        migrations.AlterModelTable(
            name='doctorsinhospital',
            table='hospital_doctors',
        ),
    ]
