# Generated by Django 5.2.5 on 2025-09-26 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_initial'),
        ('hospital', '0009_remove_billroomitem_days_remove_billroomitem_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor', to='hospital.department'),
        ),
    ]
