# Generated by Django 5.2.5 on 2025-11-21 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_initial'),
        ('hospital', '0002_alter_prescriptionitem_medicine_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorsInHospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.department')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital')),
            ],
            options={
                'verbose_name': 'hospital doctor',
                'verbose_name_plural': 'hospital doctors',
                'db_table': 'hospital_doctors',
                'ordering': ['-id'],
            },
        ),
    ]
