# Generated by Django 5.2.5 on 2025-09-09 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_alter_doctorsinhospital_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorsInHospital',
        ),
    ]
