# Generated by Django 5.2.5 on 2025-09-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_doctor_description_doctor_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Doctor fee', max_digits=10, null=True),
        ),
    ]
