# Generated by Django 5.2.5 on 2025-09-24 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receptionist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'receptionist',
                'verbose_name_plural': 'receptionists',
                'db_table': 'receptionists_receptionist',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ApprovedReceptionist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.department')),
            ],
            options={
                'verbose_name': 'approved receptionist',
                'verbose_name_plural': 'approved receptionists',
                'db_table': 'approved_receptionist',
                'ordering': ['-id'],
            },
        ),
    ]
