# Generated by Django 5.2.5 on 2025-08-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedReceptionist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'approved receptionist',
                'verbose_name_plural': 'approved receptionists',
                'db_table': 'approved_receptionist',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='receptionist',
            name='license_number',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
