# Generated by Django 5.2.5 on 2025-10-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvedreceptionist',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to='staff_image'),
        ),
    ]
