# Generated by Django 5.2.5 on 2025-10-13 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0034_token_is_lock'),
        ('receptionist', '0003_approvedreceptionist_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvedreceptionist',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='receptionist',
            name='license_number',
        ),
        migrations.AddField(
            model_name='receptionist',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.department'),
        ),
        migrations.AddField(
            model_name='receptionist',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receptionist',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='receptionist',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to='staff_image'),
        ),
        migrations.AddField(
            model_name='receptionist',
            name='specialization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
