# Generated by Django 5.2.5 on 2025-10-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0004_remove_approvedreceptionist_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionist',
            name='license_number',
            field=models.CharField(default=0, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
