# Generated by Django 5.2.5 on 2025-10-13 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0005_receptionist_license_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receptionist',
            name='license_number',
        ),
    ]
