# Generated by Django 5.2.5 on 2025-11-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'manager',
                'verbose_name_plural': 'managers',
                'db_table': 'managers_manager',
                'ordering': ['-id'],
            },
        ),
    ]
